@startuml
left to right direction

actor Admin as "Admin"

rectangle GestioneLibri {
    usecase UC1 as "Registrazione libro"
    usecase UC2 as "Modifica libro"
    usecase UC3 as "Rimozione libro"
    usecase UC4 as "Visualizzazione libro"
    usecase UC5 as "Ricerca libro"
}

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC4
Admin --> UC5

@enduml